# Waterdog Main Configuration file
# Configure your desired network settings here.


# Una lista de todos los servidores descendentes que están disponibles justo después de iniciar
# el campo de dirección se formatea usando ip: puerto
# publicAddress es opcional y se puede configurar para que los reproductores ip se puedan conectar directamente a través de
servers:
  server:
    address: 127.0.0.1:19137
    server_type: bedrock
    
  #survival:
    #address: 127.0.0.1:19138
    
  #skyblock:
    #address: 127.0.0.1:19139
    #server_type: bedrock
    
listener:

  # El Motd que se mostrará en la pestaña del servidor de un jugador y se devolverá durante el ping
  motd: Perita Global Proxy

  # El nombre que se muestra en la lista de jugadores (menú de pausa)
  name: Perita Bedrock Proxy

  # La lista de prioridades del servidor. Si los complementos no lo modifican, el proxy conectará al jugador al primero de esos servidores.
  priorities:
  - server

  # La dirección a la que vincular el servidor
  host: 0.0.0.0:19132

  # La cantidad máxima de jugadores que pueden conectarse a esta instancia de proxy
  max_players: 50

  # Asigne la ip a través de la cual un jugador se unió a un servidor específico
  # por ejemplo skywars.xyz.com => SkyWars-1
  # cuando un jugador se conecta usando skywars-xyz.com como serverIp, se conectará a SkyWars-1 directamente
  forced_hosts: {}

# Lista de permisos para jugadores que distingue entre mayúsculas y minúsculas (vacía con {})
permissions:
  TuNickDelMine:
  - waterdog.player.transfer
  - waterdog.player.list
  - waterdog.command.help
  - waterdog.command.info
  #alemiz003:
  # - waterdog.player.transfer
  # - waterdog.player.list
  # - waterdog.command.help
  # - waterdog.command.info

# Lista de permisos que cada jugador debe obtener por defecto (vacía usando [])
permissions_default: []
#- waterdog.command.help
#- waterdog.command.info

# Si la salida de depuración en la consola debe habilitarse o no
enable_debug: false

# Si está habilitado, se creará una conexión cifrada entre el cliente y el proxy
upstream_encryption: true

# Si está habilitado, solo los jugadores autenticados con XBOX Live pueden unirse. Si está deshabilitado, cualquiera puede conectarse *con cualquier nombre*
online_mode: false

# Si está habilitado, el proxy podrá vincularse a una dirección IPv6
enable_ipv6: false

# Puertos adicionales para escuchar
additional_ports: []

# Si está habilitado, el proxy pasará información como XUID o IP al servidor descendente usando campos personalizados en el LoginPacket
use_login_extras: false

# Reemplaza los espacios de nombre de usuario con guiones bajos si está habilitado
replace_username_spaces: true

# Si la consulta del servidor debe estar habilitada
enable_query: true

# Si está habilitado, al recibir un McpeTransferPacket, el proxy verificará si el servidor de destino está en la lista descendente y, en caso afirmativo, utilizará el mecanismo de transferencia rápida.
prefer_fast_transfer: true

# Fast-codec solo decodifica los paquetes requeridos por el proxy, todo lo demás se pasará sin procesar. Deshabilitar esto puede crear un impacto en el rendimiento
use_fast_codec: true

# Si está habilitado, el proxy inyectará todos los comandos de proxy en el AvailableCommandsPacket, habilitando el autocompletado
inject_proxy_commands: true

# Algoritmo utilizado para la compresión ascendente. Compatible actualmente: zlib, snappy
# Esto solo es aplicable en 1.19.30 y versiones más nuevas
compression: zlib

# Relación de compresión del servidor ascendente (proxy a cliente), mayor = menos ancho de banda, más CPU, menor viceversa
upstream_compression_level: 6

# Relación de compresión del servidor descendente (proxy a servidor descendente), mayor = menos ancho de banda, más CPU, menor viceversa
downstream_compression_level: 2

# Las funciones educativas requieren pequeños ajustes para funcionar correctamente. Habilite esta opción si alguno de los servidores posteriores admite funciones educativas.
enable_edu_features: false

# Habilitar/Deshabilitar el sistema del paquete de recursos
enable_packs: true

# Si esto está habilitado, el cliente no podrá usar paquetes personalizados
overwrite_client_packs: false

# Si está habilitado, el cliente se verá obligado a aceptar paquetes de recursos del lado del servidor
force_server_packs: false

# Puede establecer el tamaño máximo del paquete en MB para almacenar en caché.
pack_cache_size: 16

# Crear hilos puede ser costoso en algunas situaciones. Especifique el recuento mínimo de subprocesos inactivos por ejecutores de subprocesos internos. Establézcalo en -1 para la detección automática por recuento de núcleos.
default_idle_threads: -1

# Habilite las estadísticas anónimas que se envían a bstats. Para obtener más información, consulte nuestra página bstats en https://bstats.org/plugin/server-implementation/WaterdogPE/15678
enable_statistics: true
