enforce_secure_profile: false
listeners:
- query_port: 26131
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - survival
  bind_local_address: true
  host: 0.0.0.0:26131
  max_players: 1
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
  admin:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: ca70153c-b0be-4785-bce3-a1cf487bec99
player_limit: 50
ip_forward: true
groups:
  ZeroTwo8518:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: none
    address: 127.0.0.1:25565
    restricted: false
  survival:
    motd: none
    address: n1.cozecloud.in:25901
    restricted: false
